// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rxkvnzcpqxlhmslldbge.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ4a3ZuemNwcXhsaG1zbGxkYmdlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwMjA5MTIsImV4cCI6MjA2NDU5NjkxMn0.tNUCnP3LozAzF1SgVH3ililunaUQzBMSe3nGDMcePLc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);